//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videojuegos_PereraA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juego()
        {
            this.JuegoPlataforma = new HashSet<JuegoPlataforma>();
        }
    
        [Key]
        public int IdJuego { get; set; }
        [Column("Juego")]
        public string Juego1 { get; set; }
        public Nullable<int> IdTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [ForeignKey("IdJuego")]
        public virtual ICollection<JuegoPlataforma> JuegoPlataforma { get; set; }
        [ForeignKey("IdTipo")]
        public virtual Tipo Tipo { get; set; }
    }
}
