//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videojuegos_PereraA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class JuegoPlataforma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JuegoPlataforma()
        {
            this.Puntuacion = new HashSet<Puntuacion>();
        }
    
        [Key]
        public int Id { get; set; }
        public Nullable<int> IdJuego { get; set; }
        public Nullable<int> IdPlataforma { get; set; }
        public Nullable<int> IdDistribuidor { get; set; }
        public Nullable<int> IdDesarrollador { get; set; }

        [ForeignKey("IdDesarrollador")]
        public virtual Desarrollador Desarrollador { get; set; }
        [ForeignKey("IdDistribuidor")]
        public virtual Distribuidor Distribuidor { get; set; }
        [ForeignKey("IdJuego")]
        public virtual Juego Juego { get; set; }
        [ForeignKey("IdPlataforma")]
        public virtual Plataforma Plataforma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //[ForeignKey("Id")]
        public virtual ICollection<Puntuacion> Puntuacion { get; set; }
    }
}
