//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videojuegos_PereraA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Puntuacion
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> Idcliente { get; set; }
        public Nullable<int> idjuegoplataforma { get; set; }
        public Nullable<int> Puntuacion1 { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [ForeignKey("Idcliente")]    //REVISAR
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("Idjuegoplataforma")]
        public virtual JuegoPlataforma JuegoPlataforma { get; set; }
    }
}
