//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videojuegos_PereraA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Tipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo()
        {
            this.Juego = new HashSet<Juego>();
        }
    
        [Key]   //Indicamos que es la clave primaria.
        public int IdTipo { get; set; }
        [Column("Tipo")]    //Indicamos con la etiqueta Column para que busque en la base de datos por la columna Tipo, en lugar de Tipo1.
        public string Tipo1 { get; set; }   //Le chirría que haya un atributo con el mismo nombre de la clase, por lo que le asigna un 1.
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [ForeignKey("IdTipo")]
        public virtual ICollection<Juego> Juego { get; set; }
    }
}
